# Generated by Django 4.2.7 on 2023-11-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamentos',
            fields=[
                ('id_apto', models.AutoField(primary_key=True, serialize=False)),
                ('numero_apto', models.IntegerField()),
                ('morador', models.TextField(max_length=255)),
            ],
        ),
    ]
