# Generated by Django 4.2.7 on 2023-12-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentos',
            name='morador',
            field=models.CharField(max_length=255),
        ),
    ]
