# Generated by Django 4.2.7 on 2024-03-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalogo', '0002_alter_apartamentos_morador'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamentos',
            name='aluguel',
            field=models.CharField(default=1000, max_length=255),
            preserve_default=False,
        ),
    ]
